### ISSUE TITLE
After installed got error and fix app name

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/Food-Recipe-App#1]
![WhatsApp Image 2023-08-07 at 20 59 03](https://github.com/IrhamNfrnda/Food-Recipe-App/assets/49361887/18f6b8d3-927f-48f2-9be2-b3ca1dc23c7b)
![WhatsApp Image 2023-08-07 at 20 59 03 (1)](https://github.com/IrhamNfrnda/Food-Recipe-App/assets/49361887/5e1ec113-d030-41bc-9bf4-156b649cdb6e)

**Comment by IrhamNfrnda** [comment]
Fixed
