### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/Food-Recipe-App#3]
![photo_6267245772319864377_y](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/49361887/01e0d66f-490f-40b1-9834-eb74e6e8ac2c)

Please add search feature

**Comment by IrhamNfrnda** [comment]
Fixed
![Screenshot_1692580835](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/55636345/03a61b33-453e-40e1-9846-6d9ea0e55783)
