### ISSUE TITLE
Success add recipe but not showing in my recipe

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/Food-Recipe-App#4]
![photo_6267044334058714749_y](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/49361887/9e6eb180-0933-4c78-b80d-8d10b4692452)

**Comment by IrhamNfrnda** [comment]
Fixed

![Screenshot_1692580479](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/55636345/047bccf9-3923-4470-92f9-afd54dde3573)
