### ISSUE TITLE
Login success but got this alert and after app close by window need login again

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/Food-Recipe-App#5]
![photo_6267044334058714750_y](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/49361887/732a5895-4d98-41e8-bec5-63a8bae25a50)
![photo_6267044334058714748_y](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/49361887/f7d11d14-e1ac-4b98-a0b1-bda868cffe99)

Ini kayaknya kamu pake redux tapi reduxnya gak pake redux persist deh jadi datanya di simpen sementara aja jadi kalo appnya di close statenya hilang

**Comment by IrhamNfrnda** [comment]
Fixed
![Screenshot_1692580559](https://github.com/IrhamNfrnda/food-recipe-mobile/assets/55636345/6dabbb9b-409d-4017-aa2c-807ed996d9ad)
